apiVersion: "kubeflow.org/v1alpha3"
kind: Experiment
metadata:
  namespace: kubeflow
  name: jhs-pp
spec:
  parallelTrialCount: 5
  maxTrialCount: 30
  maxFailedTrialCount: 1
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: Validation-accuracy
    additionalMetricNames:
      - F1-score
      - accuracy
      - precision
      - recall      
  metricsCollectorSpec:
    collector:
      kind: StdOut
    source:
      filter:
        metricsFormat:
        - "([\\w|-]+)\\s*=\\s*((-?\\d+)(\\.\\d+)?)"        
  algorithm:
    algorithmName: random    
  parameters:
    - name: --lr
      parameterType: double
      feasibleSpace:
        min: "0.00001"
        max: "0.0001"
    - name: --epochs
      parameterType: int
      feasibleSpace:
        min: "3"
        max: "30"
    - name: --dropout
      parameterType: double
      feasibleSpace:
        min: "0.2"
        max: "0.5"
    - name: --optimizer
      parameterType: categorical
      feasibleSpace:
        list:
        - sgd
        - adam
        - rmsprop
  trialTemplate:
    goTemplate:
      rawTemplate: |-
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: {{.Trial}}
          namespace: {{.NameSpace}}
        spec:
          template:
            spec:
              containers:
              - name: {{.Trial}}
                image: modenaf360/mnist-light
                imagePullPolicy: Always
                command:
                - "python3"
                - "/opt/jhs_keras/CNN_MNIST_Light.py"
                - "--batch_size=30"
                {{- with .HyperParameters}}
                {{- range .}}
                - "{{.Name}}={{.Value}}"
                {{- end}}
                {{- end}}
              restartPolicy: Never